"""Shared column lists for RQ2 manual audit exports."""

from __future__ import annotations

RQ2_AUDIT_EVIDENCE_FIELDS = [
    "repo",
    "test_id",
    "framework",
    "line",
    "name",
    "raw_code",
    "value_summary",
    "input_source_class",
    "input_plausibility",
    "input_plausibility_paper_label",
    "input_plausibility_confidence",
    "input_plausibility_codebook_path",
    "input_plausibility_review_family",
    "input_plausibility_deterministic",
    "input_plausibility_llm",
    "input_plausibility_final",
    "input_plausibility_final_basis",
    "input_plausibility_llm_trigger_reason",
    "input_plausibility_llm_confidence",
    "input_plausibility_llm_rationale",
    "input_plausibility_llm_codebook_step",
    "input_plausibility_pre_adjudication_final",
    "input_plausibility_adjudication_label",
    "input_plausibility_adjudication_confidence",
    "input_plausibility_adjudication_trigger_reason",
    "input_plausibility_adjudication_codebook_step",
    "input_plausibility_adjudication_rationale",
    "llm_model",
    "llm_prompt_version",
    "llm_input_hash",
    "value_visibility",
    "input_channel",
    "field_context",
    "input_target_role_ast",
    "input_target_role_basis_ast",
    "input_target_context_ast",
    "input_target_context_normalized_ast",
    "input_target_context_basis_ast",
    "input_value_expression_kind_ast",
    "input_endpoint_construction_ast",
    "input_endpoint_construction_basis_ast",
    "rq2_value_bearing_input",
    "rq2_value_exclusion_reason",
    "rq2_value_bearing_basis",
    "input_origin_kind",
    "input_origin_evidence",
    "input_provenance",
    "input_provenance_family",
    "input_provenance_components_json",
    "external_file_path",
    "field_path",
    "linked_definition_file",
    "linked_definition_line",
    "input_evidence_basis",
    "input_source_confidence",
    "is_static_file_candidate",
    "needs_review",
]

PROVENANCE_AUDIT_FIELDS = ["audit_bucket", *RQ2_AUDIT_EVIDENCE_FIELDS]

REVIEW_BUNDLE_AUDIT_FIELDS = [
    "sample_origin",
    *RQ2_AUDIT_EVIDENCE_FIELDS,
    "review_reason",
    "manual_source_ok",
    "manual_plausibility_ok",
    "manual_plausibility_should_be",
    "manual_notes",
]
